version: "3"

services:
  bot:
    image: zhaozisong0/rwr-discord-bot:latest
    # rename this
    container_name: my-rwr-discord-bot
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    # merge your env
    env_file: .env